### ISSUE TITLE
Forza Telemetry fails to launch properly.

### ISSUE THREAD

**Issue by Giovani1906** [austinbaccus/forza-telemetry#33]
The program remains stuck here.
![image](https://user-images.githubusercontent.com/74223243/136160543-9cf3033f-ebd4-4409-967a-f5782414971b.png)
While running it in a terminal it gives this error.
![image](https://user-images.githubusercontent.com/74223243/136160341-4c5e2cfc-403b-4081-9aa4-0b7348207cc3.png)
I tried to build it manually as well but it gives the same error from the second image when running `npm run start` and a grey to black window.
I have installed dotnet sdk 5.0.401 and 6.0.100-rc.1.21463.6 with the x86 and x86-64 variants.

**Comment by austinbaccus** [comment]
Looking into this.

**Comment by Giovani1906** [comment]
.NET 6.0 is already installed.
I've set the UDP settings as you said, still nothing.
I'm using the Steam version of FH4 so that way of enabling UDP Loopback doesn't work in my case.
Also if I'm using python using this small script I get some data printed in a terminal.
```py
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(("127.0.0.1", 5300))
while True:
    print(sock.recvfrom(65536))
```
![image](https://user-images.githubusercontent.com/74223243/136345861-0889c26a-c0d4-468b-a293-e8d62e107b74.png)
It's a bunch of 0 bytes because it's in the main menu.

**Comment by Giovani1906** [comment]
Seems to work now.
