### ISSUE TITLE
app is not receiveing data out for forza horizon 5

### ISSUE THREAD

**Issue by blackleaf420** [austinbaccus/forza-telemetry#46]
no matter what i do app refuses to receive data sim dashboard works fine buts seems this app wont any thoughts?

**Comment by austinbaccus** [comment]
Did you get it on Steam?

**Comment by blackleaf420** [comment]
no ms store

**Comment by austinbaccus** [comment]
@blackleaf420 
Hmm, let's try this:

1. Is FH5 playing on your PC? It doesn't work on Xbox currently
2. Did you navigate to the `src` folder before running the `start` command?
3. Did you configure the Data Out settings in FH5 correctly?
- Set `Data Out` to `ON`
- Set `Data Out IP Address` to `127.0.0.1` (localhost)
- Set `Data Out IP Port` to `5300`
4. Did you enable UDP loopback?
5. Is the ForzaCore folder in your repo?

Also, I have some questions for you:
1. Does the app start?
2. How exactly is it not working? Does it boot up but doesn't show any data?

**Comment by blackleaf420** [comment]
i downloaded the latest release i did not build it so most that doesn't apply and yes thaat app launches but just sits idle like forza isnt outputting data but it is as sim dashboard will display output data and it is configured correctly

**Comment by austinbaccus** [comment]
I just downloaded the latest release and it seems to work fine for me. It did ask me to allow access to the app through Windows Firewall, though. Did you get a prompt that looks like this?

![image](https://user-images.githubusercontent.com/10345834/141204839-d98bc525-2fdf-421c-bfd1-dcf84e7b41a8.png)

You need to allow access or else it won't work.

**Comment by blackleaf420** [comment]
i went as far as disabling windows firewall and that didnt fix it :\

**Comment by austinbaccus** [comment]
Can you walk me through your process to get it working/installed step by step? Maybe there's something we're missing.

**Comment by ChaoticWeg** [comment]
I've been playing around with my own data-out integration coming off the Microsoft Store version of FH5, and found that since it's built on UWP, localhost loopback is disabled by default. I had to follow similar steps to what's described in this link to enable it, then restart the game, and as soon as the game started back up I was getting data.

https://stackoverflow.com/a/33263253

The following elevated PowerShell command should (hopefully) do the trick:

```
CheckNetIsolation LoopbackExempt -a -n="Microsoft.624F8B84B803.405.2.0_x64_8wekyb3d8bbwe"
```

**Comment by regtable** [comment]
can confirm this does not work for me with fh5 windows store edition. the id is different to listed above ^^ it is Microsoft.624F8B84B80_3.410.860.0_x64__8wekyb3d8bbwe it would seem from the "loop back tool" on main page. i did both of tghem and no data is being shown in the app. win 10
btw it never has asked me about firewall for some reason i even disabled and re enebled it which prompted old apps to re auth but this one did not.

**Comment by regtable** [comment]
never mind. i had to double check on .net6 x64 & x86 installation. then when i ran it after that it took about 5 minutes to pop up saying "allow access" i then got a generic crash error but it started to work. thanks for the app. be grat on the stream

**Comment by austinbaccus** [comment]
@blackleaf420 any updates?
