### ISSUE TITLE
Telemetry not exporting data to csv while recording in race. only in Freeroam. (FH5)

### ISSUE THREAD

**Issue by sketchytactics** [austinbaccus/forza-telemetry#48]
**Describe the bug**
Telemetry app appears to not be saving any in-race data to CSV files, they show up as blank.
Telemetry data is exporting fine for Freeroam recording.
I've double-checked the settings for data-out and they match the instructions on the repository.

**To Reproduce**
Just record in race and then look at the file. versus  
**Expected behavior**
Should be populating data in the CSV files from races.

**Desktop (please complete the following information):**
 - OS: Win-10 x64
 - Game: Forza Horizon 5

I've attached files from Freeroam versus In Race
[In Race.csv](https://github.com/austinbaccus/forza-telemetry/files/7614881/In.Race.csv)
[Freeroam.csv](https://github.com/austinbaccus/forza-telemetry/files/7614882/Freeroam.csv)
.

**Comment by austinbaccus** [comment]
I tried two things when I repro'd your steps:
1. I started recording a few seconds after the race had started (after pausing the game).
2. I started recording while I was in the pre-race menu.

Both techniques resulted in telemetry being outputted to a csv file. I did both tests in the Castillo Del Mar Street Race event, by the way.

Does this issue happen every time or just some of the time? Does this happen for every type of race? Maybe this bug only happens in special races, like the opening race at the start of the game?

**Comment by sketchytactics** [comment]
I was at the stadium circuit for this. But I just reran it again now and it
seems to be working. It may have been that I already had an active
recording that I had stopped, but forgot to reset before restarting and
starting the race.

It could be worth looking at that race again, but I may have encountered a
one-time issue.

Thanks for testing again though!
