### ISSUE TITLE
Not receiving data out from FH5

### ISSUE THREAD

**Issue by TexNat** [austinbaccus/forza-telemetry#49]
the same issue as https://github.com/austinbaccus/forza-telemetry/issues/46 however i'm on the steam version. i never got any notification from windows about the firewall but i allowed it through manually to no avail. the program starts fine and the ui comes up, but it just displays no data. everything is zero (or neutral or what have you)

I set the data out and ip address as instructed in the readme, and installed from the .zip release into C:/Program Files/Forza Telemetry
**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise Version 21H2
 - Forza Horizon 5
![image](https://user-images.githubusercontent.com/64905176/144764689-608b27ad-1be1-48fb-ba56-99625fe2a135.png)
![image](https://user-images.githubusercontent.com/64905176/144764836-88bf3ff2-59db-45fe-a813-289eba7d3a3f.png)

**Comment by austinbaccus** [comment]
Hi TexNat,

I'm currently away from my PC for a few more days, but I'll help you as best I can. 

Did you install .NET? 

The .NET/C# process is what communicates between FH5 and the UI. If .NET isn't installed, then that crucial component won't work. 

Also, did you install the release package/executable or did you clone the repo?

Also, make sure the ForzaCore folder is present in the forza-telemetry folder. That's where the .NET/C# process code is. If it's not there or in the wrong spot then the UI will not show any data from FH5.

If none of this works or you still need help I'd be happy to get on a Discord/Zoom/Teams call and help you out there too.

**Comment by TexNat** [comment]
i installed the .net runtime that was linked, and the forzacore folder is present. i installed from the release.

my discord is Texan Nationalist#0768

**Comment by fabricegeib** [comment]
> i installed the .net runtime that was linked, and the forzacore folder is present. i installed from the release.
> 
> my discord is Texan Nationalist # 0768

Hello, have you found a solution ?

**Comment by austinbaccus** [comment]
Sorry, sent a friend request. It's the week before finals week at my school and I might not be able to get around to this for a bit.

**Comment by fabricegeib** [comment]
> Sorry, sent a friend request. It's the week before finals week at my school and I might not be able to get around to this for a bit.

no problem, focus on your studies and exams 👊 see you soon

**Comment by wokes** [comment]
I've had the same issue.
I kinda fumbled it, so I'm not entirely sure what in this process made it work, but here we go:
1. Close forza and the app
2. Run the app in admin mode
3. Allow network access in the prompt that pops up
4. Launch forza

After that, I got this error:
![image](https://user-images.githubusercontent.com/23318471/146108743-a95e3dcf-f75c-44b6-927d-0b89ad908458.png)

But after ignoring it it seems to work flawlessly.

**Comment by TexNat** [comment]
Fixed, make sure you install the .NET SDK, not the Runtime.
