### ISSUE TITLE
App not receiving data from FH5

### ISSUE THREAD

**Issue by Syycorax** [austinbaccus/forza-telemetry#50]
App screen shows [no info](https://imgur.com/a/aeVsF58)

- App is running on my PC not on xbox
- .NET sdk is [installed](https://imgur.com/a/ggdVEql)
- [IP and port](https://imgur.com/a/Bw0SqFq) are correct and data transmission is on
- Enable AppContainer Loopback is running and [Forza horizon 5](https://imgur.com/a/9zVe6RV)(game pass version) is checked
- Also tried a python script found in another [issue](https://github.com/austinbaccus/forza-telemetry/issues/33#issuecomment-937559838) with the same result (0's when game is paused but actual data while the game is running)

**Comment by Luamnoxu** [comment]
Oh yea I have the same issue

**Comment by austinbaccus** [comment]
@Syycorax @Luamnoxu 

Double check that you've enabled access through the firewall. You should receive a prompt asking you to enable firewall access when you first launch the app. Make sure that's been checked. If it doesn't show up, I'd still manually double check that it's been enabled.

**Comment by Luamnoxu** [comment]
Manually enabled it in the firewall but it still does not recieve any data
is there some sort of log or something I can check to give more info

**Comment by Syycorax** [comment]
> @Syycorax @Luamnoxu 
> 
> Double check that you've enabled access through the firewall. You should receive a prompt asking you to enable firewall access when you first launch the app. Make sure that's been checked. If it doesn't show up, I'd still manually double check that it's been enabled. 

Already double checked that, even disabled the firewall entirely as a last ressort

**Comment by Luamnoxu** [comment]
firewall off still no response from the program

**Comment by austinbaccus** [comment]
@Syycorax @Luamnoxu 

Hmm. I'm not sure if I can think of anything else to fix right now, this seems like a new issue. Would either of you guys be willing to jump into a call on Discord later today? We can troubleshoot there.

**Comment by Syycorax** [comment]
Sorry for the late response,
give me your dc I'll add you 👍

**Comment by austinbaccus** [comment]
austinbaccus#9346

**Comment by Specia1** [comment]
Found a solution yet?

**Comment by austinbaccus** [comment]
> Found a solution yet?

@Specia1 We're going to troubleshoot after I get off work today. If we find a solution, we'll definitely post it within a few hours. Hang tight

**Comment by Luamnoxu** [comment]
sound
id join in too but its already 11pm and I dont think id manage however more till youre done with work 👍

**Comment by austinbaccus** [comment]
Fixed.

The solution for one user was to download the .NET 6.0 SDK. Without the SDK, ForzaCore could not run, and that's the code that listens for UDP telemetry from Forza and sends it to the GUI.

The solution for @Syycorax was to reconfigure his Nuget package manager. He could not install the ElectronCgi-DotNet Nuget package because it was messed up. Once that was fixed, he was able to install the necessary Nuget packages and run the app. He can provide a more detailed explanation soon.

**Comment by austinbaccus** [comment]
@Specia1 @Luamnoxu see the above comment for possible solutions. If none of these work, I'd be happy to get on a call with everyone and help troubleshoot (it might be some time before that though, I have a lot of stuff to do for work and I'm about to start my last semester of college in a few days).

**Comment by austinbaccus** [comment]
Here is Syycorax's solution:

1. Make sure your NodeJS version is not 17.3.0 (16.3.1 worked for us) as it seems to produce an error. You can check your version with `node -v`
2. Go through the manual installation process from the README
3. If you get an error like `Connection to dotnet was terminated (code: 1)` when running `npm run start`, then follow these steps:
4. Make sure the ForzaCore folder is present navigate into it and run dotnet run ForzaCore.csproj
5. If you get an error like error: NU1100: Unable to resolve 'ElectronCgi.DotNet (>= 1.0.3)' for 'net6.0' run dotnet nuget list source if it returns No packages found. or anything similar, check if C:\Username\.nuget exists if it does not, modify C:\Users\Username\AppData\Roaming\NuGet\NuGet.Config to look like this

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="NugetServer" value="http://myserver:12345/nuget" />
  </packageSources>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
</configuration>
```

6. Run `dotnet add package ElectronCgi.DotNet --version 1.0.3` in the ForzaCore folder
7. It should work now. Enter `npm run start` in the `src` folder to double check
