### ISSUE TITLE
forza-telemetry app never recognizes game

### ISSUE THREAD

**Issue by Caboose12000** [austinbaccus/forza-telemetry#54]
**Describe the bug**
The app opens but never displays any values from Forza.  I made sure 'Data Out' is set to 'ON', IP ADDRESS is 127.0.0.1, IP PORT is 5300, and I tried both the latest release of the exe and cloning the repo, same result both times, all values stay at 0.

**To Reproduce**
1. follow the steps in the quick start guide
2. when the app opens, it never shows data despite driving around in game

**Expected behavior**
When driving with the app open and UDP Out settings enabled, data values displayed in the app should increase or decrease depending on how the car drives in game.

**Screenshots**
I'm not sure if these screenshots are helpful, but here they are anyway
View of app not showing data:
![NoNewData](https://user-images.githubusercontent.com/64852933/174392908-0084fa92-5352-457e-a044-9945b71a9849.PNG)
View of settings (maybe I entered something wrong?):
![FH4Settings](https://user-images.githubusercontent.com/64852933/174392813-52f89bf5-cee7-4cb0-acdc-87c141927f07.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Version 21H2, OS Build 19044.1706)
 - Game Forza Horizon 4 (via steam)

**Additional context**
(again not sure any of this is helpful sorry)
- I tested FH4 UDP Out with the android mobile app 'Forza Dashboard (telemetry)' and it was able to correctly show my cars speed in real time
- Forza and both the .exe and cloned repo version of the app are on my HDD instead of the SSD that the OS boots on
- The cloned repo version said there were a bunch of npm vulnerabilities, not sure if that's related but I couldn't figure out how to fix them
- I tried installing .NET 6.0, no effect
- I tried installing the Win8 Loopback Utility (even though I'm using the steam version, idk I'm out of ideas).  Forza wasn't even listed to check or uncheck

**Thanks**
I just wanna say this app looks really cool and I'm excited to get it working on my machine!  Thanks for making it!

**Comment by gungurbuz** [comment]
i am having the same problem, really excited to use this program so hope this gets fixed

**Comment by austinbaccus** [comment]
@Caboose12000 @gungurbuz 

I'll investigate this when I get home. Ping me again if you don't hear from me in 48 hours.

**Comment by Caboose12000** [comment]
> @Caboose12000 @gungurbuz
> 
> I'll investigate this when I get home. Ping me again if you don't hear from me in 48 hours.

here's your 48-hour-later-ping!

**Comment by gungurbuz** [comment]
its been a while any news?

**Comment by gungurbuz** [comment]
oh shi forgot to ping

**Comment by austinbaccus** [comment]
@gungurbuz @Caboose12000 hey guys, sorry this took so long. I recently started a new job at Microsoft as a software engineer (woohoo!), but I haven't had as much time to work on my side projects (boo.). 

I don't have a solution so far, but I'm happy to troubleshoot this issue with you guys over Discord if needed.

I have some questions that might help narrow down the issue:
- Has the app been given firewall access? At some point you should've encountered a screen that looks like this:
![image](https://user-images.githubusercontent.com/10345834/176278951-918d1a1a-1be5-4647-99cc-1c163adb6ba8.png)
- Make sure you download the .NET 6.0 SDK, not the runtime
- Also make sure t's the x64 version of .NET SDK

**Comment by Caboose12000** [comment]
Hey congrats on your new job!  I would love some troubleshooting help when you have time, my discord is Caboose12000#3908

**Comment by austinbaccus** [comment]
@gungurbuz

This was the solution that worked for @Caboose12000: https://github.com/austinbaccus/forza-telemetry/issues/50#issuecomment-1008172636 (Ignore steps 1 and 2)

**Comment by gungurbuz** [comment]
thanks, i’ll try it tomorrow morning. Also congrats on the job! It’s always nice seeing more skilled programmers get into nice jobs

**Comment by six-shooter** [comment]
I am having the same issue, the app looks lovely and I would love it to work.

Tried everything, followed the steps.

**Comment by austinbaccus** [comment]
@six-shooter try running `dotnet --info` and see if version `6.0` pops up. If it's not in your list of installed SDKs, then that's probably the issue. Sometimes you have to delete the `dotnet` folder from Program Files (x86) for it to be correctly recognized.
