### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by StatelessCat** [austinbaccus/forza-telemetry#60]
Hi,
I cannot use the version executable because I want to the patch explained here : https://github.com/austinbaccus/forza-telemetry/issues/53 .
(cause I'm using a Cloud PC...)

I installed git and npm.
During the npm install I got several error about electron.

"npm i electron -g" Don't fix the issue.

I'm missing something?
Thanks
Raphaël Cazenave-Lévêque

**Comment by StatelessCat** [comment]
My errors on electron: https://pastebin.com/TNxM9c2n

**Comment by austinbaccus** [comment]
Try using npm v16.13.0.

**Comment by StatelessCat** [comment]
It compile ! Thanks
